name: Build iOS 13-17 Dylib

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Show Xcode & iOS SDK info
        run: |
          xcode-select --print-path
          xcodebuild -version
          xcrun --sdk iphoneos --show-sdk-path
          xcrun --sdk iphoneos --show-sdk-version

      - name: Build coruna_payload.dylib
        run: make

      - name: Ad-hoc codesign
        run: make sign

      - name: Rename to bootstrap.dylib
        run: cp coruna_payload.dylib bootstrap.dylib

      - name: Upload artifact (bootstrap.dylib)
        uses: actions/upload-artifact@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        with:
          name: bootstrap.dylib
          path: bootstrap.dylib
          retention-days: 30
